# Generated by Django 6.0.3 on 2026-03-04 06:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedNewspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('reason', models.TextField()),
                ('closed_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Closed Newspaper',
                'ordering': ['-closed_date'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('issue', models.TextField()),
                ('complaint_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Complaint',
                'ordering': ['-complaint_date'],
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Distributor',
                'ordering': ['-registered_date'],
            },
        ),
        migrations.CreateModel(
            name='NewspaperSoldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('total_received', models.PositiveIntegerField()),
                ('newspaper_details', models.JSONField(default=dict, help_text='JSON of newspaper_type: quantity taken')),
                ('total_taken', models.PositiveIntegerField(default=0)),
                ('total_sold', models.PositiveIntegerField(default=0)),
                ('total_remaining', models.PositiveIntegerField(default=0)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Newspaper Sold Record',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewspaperSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper', models.CharField(choices=[('Hindustan', 'Hindustan'), ('Dainik Jagaran', 'Dainik Jagaran'), ('Dainik Bhaskar', 'Dainik Bhaskar'), ('Prabhat Khabar', 'Prabhat Khabar'), ('AAJ', 'AAJ'), ('The Times Of India', 'The Times Of India'), ('The Hindu', 'The Hindu'), ('Hindustan Times', 'Hindustan Times')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newspaper Subscription',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('months_paid_till', models.DateField(help_text='Last month for which payment has been made')),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Record',
                'ordering': ['-last_updated'],
            },
        ),
    ]
